import { siteData } from '../lib/data.js';

export function GET() {
  const gateLines = siteData.meta.publication_blockers.map((item) => `- ${item.id} (${item.status}): ${item.summary}`);
  const lines = [
    '# Kogen Bench · bounded agent guide',
    '',
    `Data revision: ${siteData.meta.revision}`,
    `Source: https://github.com/KogenAI/kogen-bench/tree/${siteData.meta.revision}`,
    '',
    'Numeric values copied from source narrative remain source-reported. Claim values are transcribed from the claim ledger with their original status and evidence label. No results are recomputed or pooled here.',
    '',
    '## Start here',
    '- [Findings](https://bench.kogen.dev/findings/)',
    '- [Hypotheses](https://bench.kogen.dev/hypotheses/)',
    '- [Experiments](https://bench.kogen.dev/rounds/)',
    '- [Comparisons](https://bench.kogen.dev/comparisons/)',
    '- [Evidence map](https://bench.kogen.dev/evidence/)',
    '- [Publication validation](https://bench.kogen.dev/publication-validation/)',
    '- [Methods](https://bench.kogen.dev/methods/)',
    '- [Reproduce](https://bench.kogen.dev/reproduce/)',
    '- [Verify published numbers](https://bench.kogen.dev/verify/)',
    '- [Rerun and regrade tasks](https://bench.kogen.dev/rerun/)',
    '- [Credits](https://bench.kogen.dev/credits/)',
    '- [Data](https://bench.kogen.dev/data/)',
    '',
    '## Publication evidence status',
    ...gateLines,
    '- The refreshed public official grade export exact-joins all 5,020 of 5,020 captured graded IDs. Its 128 post-cut additions comprise 84 model PASS, 19 model FAIL, and 25 invalid control_apply rows (result=invalid/outcome=fail); controls are not model failures. Publication gate states are listed above; B2 locally verifies the pinned v1.2 specification fragments cited by EVIDENCE-MAP.md. The absent decision ledger means comprehensive decision-to-clause coverage remains limited.',
    '- [GRADE-JOIN.md](https://github.com/KogenAI/kogen-bench/blob/' + siteData.meta.revision + '/results/GRADE-JOIN.md) documents the refreshed exact public matches and post-cut row classification.',
    '- [Full validation report](https://bench.kogen.dev/publication-validation/)',
    '',
    '## Findings',
    ...siteData.findings.flatMap((item) => [`### ${item.id} — ${item.title}`, '', `Source summary: https://bench.kogen.dev/findings/${item.slug}/`, '']),
    '## Hypothesis register',
    ...siteData.hypotheses.flatMap((item) => [`- ${item.id} (${item.family_id}; ${item.status}): ${item.proposition} — https://bench.kogen.dev/hypotheses/${item.slug}/`]),
    '',
    '## Round register',
    ...siteData.rounds.map((item) => `- ${item.id} (${item.status}; ${item.family_ids.join(', ') || 'family not linked'}): ${item.title} — https://bench.kogen.dev/rounds/${item.slug}/`),
    '',
    '## Claim ledger index',
    ...siteData.claims.map((item) => `- ${item.claim_id} (${item.claim_status || 'status not recorded'}; ${item.evidence_status || 'evidence status not recorded'}; ${item.metric || 'metric not recorded'}): https://bench.kogen.dev/claims/${item.claim_id.toLowerCase()}/`),
    '',
    '## Evidence map',
    ...siteData.evidence.map((item) => `- ${item.title}: https://bench.kogen.dev/evidence/${item.id}/`),
    '',
    '## Data and methods',
    '- [METHOD.md](https://github.com/KogenAI/kogen-bench/blob/' + siteData.meta.revision + '/METHOD.md)',
    '- [STANDARD.md](https://github.com/KogenAI/kogen-bench/blob/' + siteData.meta.revision + '/STANDARD.md)',
    '- [reproduce/README.md](https://github.com/KogenAI/kogen-bench/blob/' + siteData.meta.revision + '/reproduce/README.md)',
    '- [Downloads](https://bench.kogen.dev/data/)',
    '- [Machine index](https://bench.kogen.dev/index.json)',
    '- [Snapshot hashes](https://bench.kogen.dev/snapshot.json)',
    '',
  ];
  return new Response(lines.join('\n'), { headers: { 'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff' } });
}
