name = "durable_queue"
version = "1.0.0"
target = "erlang"
gleam = ">= 1.18.1"

[dependencies]
gleam_stdlib = { path = "vendor/gleam_stdlib" }
gleam_json = { path = "vendor/gleam_json" }
gleam_erlang = { path = "vendor/gleam_erlang" }

[dev-dependencies]
gleeunit = { path = "vendor/gleeunit" }
