name = "refstore"
version = "0.1.0"
target = "erlang"

[dependencies]
gleam_stdlib = { path = "vendor/gleam_stdlib" }
gleam_json = { path = "vendor/gleam_json" }

[dev-dependencies]
gleeunit = { path = "vendor/gleeunit" }
